spring:
  datasource:
    username: root
    password: gengrui
    url: jdbc:mysql://localhost:3306/tdd?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource